# Generated by Django 5.1.7 on 2025-03-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0002_alter_user_user_type_companyprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_amount',
            new_name='bidding_price',
        ),
        migrations.AddField(
            model_name='bid',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
