# Generated by Django 5.1.7 on 2025-03-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0004_bidconfirmation_tenderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Company description and background information', null=True),
        ),
    ]
