# Generated by Django 5.1.7 on 2025-03-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0005_companyprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
