# Generated by Django 5.1.7 on 2025-03-23 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0006_bid_awarded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='winning_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tenders', to='tender_app.bid'),
        ),
    ]
