# Generated by Django 5.1.7 on 2025-03-23 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender_app', '0007_tender_winning_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderhistory',
            name='field',
            field=models.CharField(blank=True, help_text='Fields that were changed', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenderhistory',
            name='new_value',
            field=models.TextField(blank=True, help_text='New value after change', null=True),
        ),
        migrations.AddField(
            model_name='tenderhistory',
            name='old_value',
            field=models.TextField(blank=True, help_text='Previous value before change', null=True),
        ),
        migrations.AddField(
            model_name='tenderhistory',
            name='user',
            field=models.CharField(blank=True, help_text='User email or identifier', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenderhistory',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tenderhistory',
            name='changes',
            field=models.JSONField(blank=True, default=dict, help_text='JSON representation of the changes made'),
        ),
        migrations.AlterField(
            model_name='tenderhistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
